add check for navigator
insin/react-maskedinput pull request #83
Opened 2016-12-15 01:57 UTC by aesopwolf

This enables server side rendering

2016-12-15 02:36 UTC, iamdustan commented on src/index.js
> +    if (navigator) {
can you do a `typeof navigator !== 'undefined'` check? strict mode would still throw on this.

2016-12-15 02:38 UTC, iamdustan requested changes

2016-12-15 02:38 UTC, iamdustan commented on src/index.js
> +    return
let’s return `onKeyPress` as a fallback. In case someone is doing something terribly weird and deleting or hiding `navigator` from the global scope.

2016-12-15 02:46 UTC, iamdustan approved these changes

2016-12-15 02:48 UTC, merged

2016-12-15 02:50 UTC, iamdustan commented
Published as 3.3.4. Thanks!

2016-12-17 00:32 UTC, avindra commented
@aesopwolf I would recommend mocking `navigator`. User agent is typically a header sent by browsers anyway, and for isomorphic code you would want `navigator.userAgent` to be available on the server side.

2016-12-17 01:25 UTC, aesopwolf commented
What would be the purpose of mocking `navigator` on the server within the context of this function? The server has no business setting up event handlers.

2016-12-17 14:53 UTC, avindra commented
In this context of this function, it has no meaning, but other libraries could potentially be rendering different DOM attributes or altogether different subtrees. -