Allow the enter key to trigger an onSubmit callback with the event.
insin/react-maskedinput pull request #89
Opened 2017-01-29 19:41 UTC by briantrice

This allows a project I'm working on to use MaskedInput but submit values with the enter key even if not embedded in a proper form. It feels reasonable to use but I haven't tested many scenarios outside what we've envisioned.

2017-01-30 11:27 UTC, antoniotaha requested changes

2017-01-30 11:27 UTC, antoniotaha commented on src/index.js
> +    }
Do you test this in firefox? The key is NULL when I press enter in the field.

2017-05-30 15:08 UTC, antoniotaha commented on src/index.js
> +    }
- Verify #90

2018-03-27 18:09 UTC, tsnieman commented
Why hasn't this been merged? @insin Any insights? I'm happy to update this PR if that's all that's stopping us from getting this change into `react-maskedinput`.

2018-04-20 18:57 UTC, briantrice commented
I am no longer using this React component, so @tsnieman you are welcome to take this over.

2019-05-20 20:44 UTC, closed without merging